### PR TITLE
[cobrand] Fix color contrast a11y for radio button controls

### PR DESCRIPTION
**Pull request by peterk**
MS Accessibility insights reports an accessibility error (color contrast too low) for radio buttons with text. Changed color for active selection to white (#fff) instead of #222 in the fixamingata cobrand. E.g.:

image

image

### CODE REVIEW

**Comment by jonkri** [comment]
Hi, @peterk!

Thank you for your contribution to FixaMinGata!

By coincidence, we had been working on some color and contrast changes on our own when you submitted your pull request, and we recently shipped these on https://fixamingata.se (https://github.com/Sambruk/fixmystreet/commit/0d58f185d02de53e3c79de135ad5f3007e0420d6#diff-f6b8f7738ca49309d56ad3dcf7f52caa2848131f853d895179607af2be00a251R222 is the change related to the buttons).

The buttons now look like this:

Screenshot of FixaMinGata's new buttons

Do you think the contrast/design changes we made work well enough?

**Comment by peterk** [comment]
Doing a [quick calculation](https://webaim.org/resources/contrastchecker/) in relation to WCAG AA (picking the darkest color in the linear background fill) it seems to barely pass for large text. It would be great if background could be darkened a bit more.

**Comment by jonkri** [comment]
Thanks!

Any thoughts on these colors?

I incrementally increased the black/Key(K in CMYK) color values by 5:

`@include button-variant(#1eafd1, #077594, #077594, #fff, #056782, #1eafd1, #077594, #fff);` (5):

darker-button-5

`@include button-variant(#1ca4c4, #066b87, #066b87, #fff, #055d75, #1ca4c4, #066b87, #fff);` (10):

darker-button-10

`@include button-variant(#1a9ab8, #05617a, #05617a, #fff, #045369, #1a9ab8, #05617a, #fff);` (15):

darker-button-15

**Comment by jonkri** [comment]
Thanks again for bringing this up!

The color issue is hopefully fixed in 8f0c26ea92f873ff21c6c0cd47323436f0ad91fa. I went with the third (highest contrast) option above.

Please let us know if we can improve the accessibility of FixaMinGata further!

Closing.

**Comment by peterk** [comment]
Sorry I didn't have time to reply to your last question. Great that you have implemented an improvement!

**Pull request closed without merging**
